name: Python script
on:
  workflow_dispatch:
  schedule:
    - cron: '2 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install feedparser pandas 
      - name: Run python file
        env: 
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python ./main.py
